### ISSUE TITLE
Node.js 16으로 배포할 수 없는 문제

### ISSUE THREAD

**Issue by rocky112358** [HeXA-UNIST/hexa-blog#8]
블로그에서 사용하는 패키지 버전이 Node.js 16버전과 호환되지 않는 것 같습니다. [참고한 블로그](https://katie0809.github.io/2021/10/25/update-hexo-icarus/)
지금 LTS 지원중인 Node.js 16버전에서 배포할 수 있도록 패키지 버전 조정이 필요합니다.

**Comment by rocky112358** [comment]
hexo를 비롯한 모듈들의 메이저 버전을 올려보고있는데... 의도치 않게 푸시할때마다 dependabot이 알림을 보내는듯합니다...
현재는 알림 안오게 꺼뒀습니다.

아래는 현재 package.json 파일 내용입니다
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-cli": "^1.1.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-include": "^1.1.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^5.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^3.0.0"
  }
}
```

로컬에서 `hexo server` 명령어로 서버 띄워보면 수정 이전과 다름없이 잘 표시되는데, 배포하고나면 사이트가 와장창합니다.

---
![image](https://user-images.githubusercontent.com/6457345/166148241-fbb8e220-608f-43c3-aeb1-89e21d0ac59e.png)
---

최근에 hexo 사용해보신 분이나 잘 아시는 분의 도움이 필요합니다 ㅠㅠ

최후의 수단으로는 hexo 최신버전으로 init해서 현재 내용물들을 거기에 옮겨심어서 재현하는 방식도 시도해보려고 합니다.

**Comment by rocky112358** [comment]
해결하고 배포 완료했습니다
next 테마의 dependency가 배포과정에서 설치되지 않는 것이 문제였습니다.

* next 테마를 로컬에 두지 않고, npm install로 설치하게 해서 해당 테마의 dependency도 설치하도록 했습니다.
* 테마 config를 프로젝트 루트에 `_config.next.yml`로 옮겼습니다.
* hexo 버전을 6버전으로 업데이트했습니다.

**Comment by junwha** [comment]
수고 많으셨습니다!!
